name: service-test
version: '0.1'
summary: Run a service
description: Test of disabling service in install hook
grade: stable
confinement: strict
# passthrough:
#   base: core18

apps:
  simple:
    command: sleep 60
    daemon: simple
  forking:
    command: sh -c "sleep 60 &"
    daemon: forking

parts:
  scripts:
    plugin: nil
